const data = {
  products: [
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Adidas Fit Shirt",
      slug: "Adidas-slim-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 110,
      countInStock: 11,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Nike Slim Pant",
      slug: "nike-slim-pant",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 180,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality Pant",
    },
    {
      name: "Adidas Fit Pant",
      slug: "Adidas-fit-pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 200,
      countInStock: 10,
      brand: "Nike",
      rating: 4.0,
      numReviews: 10,
      description: "high quality Pant",
    },
  ],
};

export default data;
